staging:
  user: user
  stage: staging
  branch: staging
  deploy_path: /var/www/charity-streamlabs
  identityFile: ~/.ssh/id_rsa
  
production:
  user: user
  stage: production
  branch: production
  deploy_path: ~/var/www/charity-streamlabs
  identityFile: ~/.ssh/id_rsa